<<<<<<< HEAD
import './globals.css';
import Providers from './providers'; // 👈 import this

export const metadata = {
  title: 'Doctor Manager',
  description: 'Doctor-patient management system',
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 73417577dec493477156b1aa73d13ac556e62453
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>
        <Providers>{children}</Providers>
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> 73417577dec493477156b1aa73d13ac556e62453
      </body>
    </html>
  );
}
